export const projects = [
  {
    technologies: [],
    id: "1",
    title: "Task Manager",
    image: "/",
    description:"A web app to manage tasks with user authentication. Users can create, update, delete, and categorize tasks, while tracking progress. The app supports multi-user collaboration and uses MongoDB for storing tasks and user data.",
    link: "/",
  },
  {
    technologies: [],
    id: "1",
    title: "Online Blogging App",
    image: "/",
    description: "A platform where users can write and publish blogs, leave comments, and follow other bloggers. It features user authentication, rich-text editing, and a dynamic dashboard to track posts and interactions, with MongoDB for storing content.",
    link: "/",
  },
  {
    technologies: [],
    id: "1",
    title: "An E-commerce store",
    image: "/",
    description: "A fully functional online store that allows users to browse products, add items to their cart, and checkout. Admin users can manage products and orders. MongoDB handles product details, and Stripe can be integrated for payments.",
    link: "/",
  },
  {
    technologies: [],
    id: "1",
    title: "A Social-media App",
    image: "/",
    description: "A social network app where users can post updates, follow friends, comment on posts, and share media. Real-time chat functionality can be added. MongoDB is used to store user profiles, posts, and comments.",
    link: "/",
  },
  {
    technologies: [],
    id: "1",
    title: "Event Management App",
    image: "/",
    description: "A platform for creating, browsing, and RSVP’ing to events. Admins can manage events, and users can see upcoming events, register, and leave reviews. The backend uses MongoDB for storing event details and user data.",
    link: "/",
  },
//   {
//     technologies: [],
//     id: "1",
//     title: "",
//     image: "/",
//     description: "",
//     link: "/",
//   },
];
